defaults:
  - override hydra_logging: colorlog
  - override job_logging: colorlog

run:
  dir: ${paths.output_dir}
sweep:
  dir: ${paths.resource_dir}/outputs/
  subdir: ${hydra:job.override_dirname}

job_logging:
  handlers:
    file:
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
  root:
    level: DEBUG
  verbose: true
