external_datasets:
  # - thedrcat/daigt-proper-train-dataset
  # - radek1/llm-generated-essays
  # - alejopaullier/daigt-external-dataset
  # - carlmcbrideellis/llm-7-prompt-training-dataset
  - thedrcat/daigt-v2-train-dataset
