# path to root directory
root_dir: /workspace

# path to resources directory
resource_dir: ${paths.root_dir}/resources
notebooks_dir: ${paths.root_dir}/notebooks
input_dir: ${paths.resource_dir}/inputs
output_dir: ${paths.resource_dir}/outputs/${hydra:job.override_dirname}
artifact_dir: ${paths.output_dir}/artifacts # output artifacts
misc_dir: ${paths.resource_dir}/misc

inference_dir: ${paths.artifact_dir} # inference output
submission_dir: ${paths.artifact_dir}
