# Use the following paths for inference in Kaggle code competitions:

# path to root directory
root_dir: /kaggle/working

# path to resources directory
resource_dir: ${paths.root_dir}
input_root_dir: /kaggle/input
input_dir: ${paths.input_root_dir}/${meta.competition}

output_dir: ??? # set your uploaded dataset name (...)
misc_dir: ${paths.resource_dir}/misc

submission_dir: ${paths.root_dir} # submission output
