_target_: src.lightning.model.lt_module.CustomLitModule
compile_model: true

net:
  _target_: src.lightning.model.components.text_transformer.DefaultModel
  model_name: ${model_name}
  num_labels: 1
  gradient_checkpointing_enable: false
  pretrained: true

criterion:
  _target_: torch.nn.BCEWithLogitsLoss

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 1e-5
  weight_decay: 0.01

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 0
  num_cycles: 0.5
