# @package _global_

defaults:
  - _self_
  - meta: default
  - paths: default
  - hydra: default
  - kaggle: default
  - lightning/data: default
  - lightning/model: default
  - lightning/callbacks: default
  - lightning/trainer: default
  - lightning/logger: default
  - cv: default
  - experiment: ???
