defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "best"
  monitor: "val/auroc"
  mode: "max"
  save_last: false
  auto_insert_metric_name: False

early_stopping:
  monitor: "val/auroc"
  patience: 2
  mode: "max"

model_summary:
  max_depth: -1
