# =========================================
# Preprocess
# =========================================
extract_raw_features_task:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: src.imker.tasks.preprocess.ExtractRawFeaturesTask
    init_params:
      base_columns: []
    cache: True

text_cleansing_task:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: src.imker.tasks.preprocess.TextCleansingTask
    init_params:
      stemmer:
        _target_: nltk.stem.PorterStemmer
    cache: True

tfidf_vectorize_task_01:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: cuml.feature_extraction.text.TfidfVectorizer
    init_params:
      ngram_range: [3, 5]
    cache: True

count_vectorize_task_01:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: cuml.feature_extraction.text.CountVectorizer
    init_params:
      ngram_range: [1, 5]
    cache: True

svd_decompose_task_01:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: sklearn.decomposition.TruncatedSVD
    init_params:
      n_components: 1000
    cache: True

# =========================================
# Model
# =========================================
logistic_regression_task_01:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: sklearn.linear_model.LogisticRegression
    init_params:
      C: 1.0
      random_state: ${seed}

knn_classifier_task_01:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: sklearn.neighbors.KNeighborsClassifier
    init_params:
      n_neighbors: 100

knn_classifier_task_02:
  _target_: imker.Task
  config:
    _target_: imker.TaskConfig
    task:
      _target_: hydra.utils.get_class
      path: sklearn.neighbors.KNeighborsClassifier
    init_params:
      n_neighbors: 1000
